### ISSUE TITLE
DistributedOptimizer 梯度聚合，疑问

### ISSUE THREAD

**Issue by EthanChen1234** [alibaba/Megatron-LLaMA#12]
我们观察到DistributedOptimizer的集合通信在梯度聚合较小的情况下，将引入极大的额外开销。极端情况下，不使用梯度聚合，将引入超过整体耗时50%的额外开销。

请教下，『梯度聚合较小』可以详细解释么？

**Comment by EthanChen1234** [comment]
模型大小、并行策略固定后，采用 DistributedOptimizer 优化器，通信量是固定的吧。

**Comment by li-yi-dong** [comment]
![image](https://github.com/alibaba/Megatron-LLaMA/assets/73142299/9de778d9-d195-4cb8-84dd-001589adca4a)
红框是梯度聚合为4的一个step，蓝框是其中一个micro step，绿框是`DistributedOptimizer`

**Comment by silingtong123** [comment]
> ![image](https://user-images.githubusercontent.com/73142299/267842925-53fb03e9-4f50-4a9a-b957-ab23bb097596.png)
> 
> 红框是梯度聚合为4的一个step，蓝框是其中一个micro step，绿框是`DistributedOptimizer`
> 
> 如果减小梯度聚合，绿框不会变，红框中的蓝框数量变少，`DistributedOptimizer`耗时占整体耗时的比例就会变高。

那新的optmizizer中GA是如何影响的呢？有类似的图吗
