### ISSUE TITLE
训练完后，将保存的Megatron格式转成HF格式报错

### ISSUE THREAD

**Issue by 13416157913** [alibaba/Megatron-LLaMA#20]
执行sh tools/checkpoint_conversion/megatron_to_hf.sh进行转换；megatron_to_hf.sh如下：
python tools/checkpoint_conversion/llama_checkpoint_conversion.py \
--convert_checkpoint_from_megatron_to_transformers \
--load_path "/xxx/megatron-llama-2-7b-checkpoint_TP2" \
--save_path "/xxx/megatron-llama-2-7b-checkpoint_TP2/megatron-to-hf" \
--target_tensor_model_parallel_size 2 \
--target_pipeline_model_parallel_size 1 \
--target_params_dtype "fp16" \
--make_vocab_size_divisible_by 1 \
--print-checkpoint-structure \
--megatron-path "/xxx/Megatron-LLaMA"
========================================================================
报错信息：
Loading Megatron-LM checkpoint arguments from: /xxx/megatron-llama-2-7b-checkpoint_TP2/iter_0001000
Loading Megatron-LM checkpoint arguments from: /xxx/megatron-llama-2-7b-checkpoint_TP2/iter_0001000/mp_rank_00/model_optim_rng.pt
Traceback (most recent call last):
  File "/xxx/Megatron-LLaMA/tools/checkpoint_conversion/llama_checkpoint_conversion.py", line 847, in <module>
    main()
  File "/xxx/Megatron-LLaMA/tools/checkpoint_conversion/llama_checkpoint_conversion.py", line 841, in main
    convert_checkpoint_from_megatron_to_transformers(args)
  File "/xxx/Megatron-LLaMA/tools/checkpoint_conversion/llama_checkpoint_conversion.py", line 324, in convert_checkpoint_from_megatron_to_transformers
    state_dict = torch.load(rank0_checkpoint_path, map_location="cpu")
  File "/xxx/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/xxx/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/xxx/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'megatron'

**Comment by li-yi-dong** [comment]
--megatron-path "/xxx/Megatron-LLaMA/megatron"

**Comment by 13416157913** [comment]
添加--megatron-path "/xxx/Megatron-LLaMA/megatron"也是报一样的错误；

**Comment by 13416157913** [comment]
我试过hf-to-megatron，然后接着就执行megatron-to-hf是通的（不进行预训练），可以还原文件。

**Comment by li-yi-dong** [comment]
我们修复下

**Comment by li-yi-dong** [comment]
Fixed by https://github.com/alibaba/Megatron-LLaMA/commit/c28758e8995cf4d50aeb633da236359487516e7b

**Comment by 13416157913** [comment]
验证转换成功了，多谢，不过--megatron-path值还是"/xxx/Megatron-LLaMA“，不用改成"/xxx/Megatron-LLaMA/megatron"。

**Comment by 13416157913** [comment]
> Fixed by [c28758e](https://github.com/alibaba/Megatron-LLaMA/commit/c28758e8995cf4d50aeb633da236359487516e7b)

验证转换成功了，多谢，--megatron-path值还是"/xxx/Megatron-LLaMA“，不用改成"/xxx/Megatron-LLaMA/megatron"。
