### ISSUE TITLE
在A800*8卡的机器上，开启 overlapped-distributed-optimizer  的速度比开启 use-distributed-optimizer 的慢约8%

### ISSUE THREAD

**Issue by tingkuanpei** [alibaba/Megatron-LLaMA#22]
使用 LLaMA_13_standalone.sh 脚本运行，速度为 1962.9 token/sec/GPU。将脚本中的 “--overlapped-distributed-optimizer \ --reduce-bucket-size=2e8 \  --no-gradient-accumulation-fusion \” 删除，替换成 “--use-distributed-optimizer \”，运行速度为 2124.7 token/sec/GPU。

请问这是否符合预期，OverlappedDistributedOptimizer 比 DistributedOptimizer 快的结论仅适用于 256xA100 80GB吗？在 256xA800 80GB 上是否拥有同样的加速比？

**Comment by li-yi-dong** [comment]
`OverlappedDistributedOptimizer` 适用于受GlobalBatchSize 限制，无法使用较大的grad_accumulation 的情况。

单机的话--use-distributed-optimizer 确实会快一些。

我们在A100 和A800 上观察到的吞吐几乎一样。

**Comment by tingkuanpei** [comment]
我在16机 * A800  80 GB * 8卡的机器上测试数据如下表，网络规格为：卡和卡之间通过 NV Link互联，机器间通过 4 * 200Gbps IB 网卡互联。

模型：llama 13B
运行参数为：seq length =2048, bf16，batch size per device = 2
运行环境为：torch==2.0.1，flash-atten==2.0.4（修改代码支持了 flash attention 2）


  | global batch size | 吞吐(token per second, per device) | 显存(MiB) | GPU使用率(%)
-- | -- | -- | -- | --
Megatron-LLaMA with DistributedOptimizer | 1024 | 1885.8 | 66438 | 99~100
Megatron-LLaMA with OverlappedDistributedOptimizer | 1024 | 1126.3 | 44028 | 99~100
Megatron-LLaMA with DistributedOptimizer | 2048 | 2045.4 | 66870 | 99~100
Megatron-LLaMA with OverlappedDistributedOptimizer | 2048 | 1142.1 | 43710 | 99~100


在此环境下，Megatron-LM 默认的 DistributedOptimizer 实现，比 OverlappedDistributedOptimizer 快80%。请问这是否符合预期呢？请问我应该如何复现你们 benchmark 的速度呢？

**Comment by tingkuanpei** [comment]
我在 128 卡 x A800 80G机器上 benchmark 结果如下表所示。

模型：llama 13B
网络环境：GPU 之间通过 NVLink 互联，机器间通过 4x200Gbps IB 网卡互联
运行环境：torch==2.0.1，flash-attn==2.0.4 (修改代码，支持 flash attention 2)
运行参数：seq length = 2048，bf16，tp=2，pp=1

  | CUDA_DEVICE_MAX_CONNECTIONS | global batch size | batch size per device | OverlappedDistributedOptimizer | 吞吐(token per second, per device) | 显存(MiB) | GPU使用率(%)
-- | -- | -- | -- | -- | -- | -- | --
Megatron-LLaMA | 1 | 1024 | 2 | false | 1885.8 | 66438 | 99~100
Megatron-LLaMA | not set | 1024 | 4 | true | 1911.4 | 66898 | 99~100
Megatron-LLaMA | 1 | 2048 | 2 | false | 2045.4 | 66870 | 99~100
Megatron-LLaMA | not set | 2048 | 4 | true | 1959.1 | 66248 | 99~100

在 128 卡的环境下，global batch size = 1024时，开启 OverlappedDistributedOptimizer 相比于默认实现快 1.4%；global batch size = 2048时，反而会慢 4.4%。请问这是否符合你们的预期呢？OverlappedDistributedOptimizer 需要在 256 或 512卡环境，才会有稳定明显的加速效果吗？

**Comment by li-yi-dong** [comment]
基本符合，因为你的测试里grad accumulation 较大。
可以看看这个，大致说明了一下GA 对原optimizer 的影响https://github.com/alibaba/Megatron-LLaMA/issues/12#issuecomment-1718699839

**Comment by silingtong123** [comment]
> 使用 LLaMA_13_standalone.sh 脚本运行，速度为 1962.9 token/sec/GPU。将脚本中的 “--overlapped-distributed-optimizer \ --reduce-bucket-size=2e8 \ --no-gradient-accumulation-fusion \” 删除，替换成 “--use-distributed-optimizer \”，运行速度为 2124.7 token/sec/GPU。
> 
> 请问这是否符合预期，OverlappedDistributedOptimizer 比 DistributedOptimizer 快的结论仅适用于 256xA100 80GB吗？在 256xA800 80GB 上是否拥有同样的加速比？
你测试的时候只改了这个参数吗？有修改其他参数吗？我测试32卡发现OverlappedDistributedOptimizer吞吐比原生慢了25%

**Comment by silingtong123** [comment]
你测试的时候只改了这个参数吗？有修改其他参数吗？我测试32卡发现OverlappedDistributedOptimizer吞吐比原生慢了25%

**Comment by tingkuanpei** [comment]
> 你测试的时候只改了这个参数吗？有修改其他参数吗？我测试32卡发现OverlappedDistributedOptimizer吞吐比原生少了25%（2000 -> 1500）

@silingtong123 我修改的参数都在表里列出来了，另外，我后来发现 --reduce-bucket-size 对速度也会有较为明显的影响。可以修改这个参数试试。

**Comment by silingtong123** [comment]
@tingkuanpei 我也是按列表里改的，直接使用的 后面又把--reduce-bucket-size改成了4e10，结果变化不大
