### ISSUE TITLE
NGC22.08 环境报错。

### ISSUE THREAD

**Issue by EthanChen1234** [alibaba/Megatron-LLaMA#23]
采用NGC22.08 镜像，module 'torch.distributed' has no attribute 'reduce_scatter_tensor'

<img width="728" alt="image" src="https://github.com/alibaba/Megatron-LLaMA/assets/45474996/5ea6983d-4af2-4b0d-b1a5-9124516c8897">
自带torch是1.13.0a0+d321be6，重新安装torch会导致apex报错。

请问下：
1）有推荐的NGC镜像么
2）有没有Dockerfile

**Comment by li-yi-dong** [comment]
我在torch 1.13 的文档里可以找到这个方法，https://pytorch.org/docs/1.13/distributed.html?highlight=reduce_scatter_tensor#torch.distributed.reduce_scatter_tensor

**Comment by EthanChen1234** [comment]
@li-yi-dong 升级到 ngc23.01，就可以了
