### ISSUE TITLE
请教下为什么使用overlapped_distributed_optimizer后，CUDA_DEVICE_MAX_CONNECTIONS就可以不为1了？

### ISSUE THREAD

**Issue by yinzhijian** [alibaba/Megatron-LLaMA#26]
```python
    if os.environ.get('CUDA_DEVICE_MAX_CONNECTIONS') != "1" \
        and not args.overlapped_distributed_optimizer:
        if args.sequence_parallel:
            raise RuntimeError(
                "Using sequence parallelism requires setting the environment variable "
                "CUDA_DEVICE_MAX_CONNECTIONS to 1")
        if args.async_tensor_model_parallel_allreduce:
            raise RuntimeError(
                "Using async gradient all reduce requires setting the environment "
                "variable CUDA_DEVICE_MAX_CONNECTIONS to 1")
```
请教下大佬，为什么使用overlapped_distributed_optimizer后，CUDA_DEVICE_MAX_CONNECTIONS就可以不为1了？

**Comment by li-yi-dong** [comment]
CUDA_DEVICE_MAX_CONNECTIONS=1 会导致，即使DP 的通信在单独的Stream，且其它Stream 与其没有依赖关系的情况下，其它Stream 上的kernel 也会等DP 的通信结束后才开始执行。你可以加上这个环境变量trace 一下。

**Comment by Infi-zc** [comment]
> CUDA_DEVICE_MAX_CONNECTIONS=1 会导致，即使DP 的通信在单独的Stream，且其它Stream 与其没有依赖关系的情况下，其它Stream 上的kernel 也会等DP 的通信结束后才开始执行。你可以加上这个环境变量trace 一下。

请教下为啥 seq_parallel 强制这个值为 1 呢？

**Comment by li-yi-dong** [comment]
> > CUDA_DEVICE_MAX_CONNECTIONS=1 会导致，即使DP 的通信在单独的Stream，且其它Stream 与其没有依赖关系的情况下，其它Stream 上的kernel 也会等DP 的通信结束后才开始执行。你可以加上这个环境变量trace 一下。
> 
> 请教下为啥 seq_parallel 强制这个值为 1 呢？

CUDA_DEVICE_MAX_CONNECTIONS=1 可以让多个stream 上没有依赖关系的kernel，实际执行顺序与launch 顺序一致。seq_parallel 下可以保证反向可并行的部分集合通信先执行，并行程度更高，整体耗时更少。不影响计算结果的正确性。

**Comment by Richie-yan** [comment]
@li-yi-dong 
那这里就会有个不兼容的地方：
tp之间反向通信为了能与反向计算overlap 需要设置CUDA_DEVICE_MAX_CONNECTIONS=1
但是 dp reduce_scatter 与 反向计算overlap 需要设置CUDA_DEVICE_MAX_CONNECTIONS>1，否则观察trace 不会overlap
有什么方法可以解决这个问题吗？

**Comment by li-yi-dong** [comment]
> @li-yi-dong 那这里就会有个不兼容的地方： tp之间反向通信为了能与反向计算overlap 需要设置CUDA_DEVICE_MAX_CONNECTIONS=1 但是 dp reduce_scatter 与 反向计算overlap 需要设置CUDA_DEVICE_MAX_CONNECTIONS>1，否则观察trace 不会overlap 有什么方法可以解决这个问题吗？

目前是的，会带来一定的性能损失。
overlapped_distributed_optimizer 为了节省显存，引入了一些拷贝梯度的操作。CUDA_DEVICE_MAX_CONNECTIONS=1时，在TP 的计算stream 与DP 的通信stream 间，间接引入了依赖关系。如果能有更好的显存分配策略，可以去掉这个依赖关系，目前我们也在尝试。
