### ISSUE TITLE
4台A100*8测试，开启 overlapped-distributed-optimizer 的速度比开启 use-distributed-optimizer 慢很多

### ISSUE THREAD

**Issue by silingtong123** [alibaba/Megatron-LLaMA#27]
4台A100*8测试，开启 overlapped-distributed-optimizer 的速度比开启 use-distributed-optimizer 慢很多,测试只将脚本中--overlapped-distributed-optimizer 替换成--use-distributed-optimizer，这测试结果合理吗？

TP=2, PP=1 测试结果如下：
-- overlapped-distributed-optimizer 
global-bs 2048 micro-bs 4
elapsed time per iteration (ms): 82897.1 | average overall token/sec : 50596.5 | average token/sec/GPU : 1581.1 GPU显存使用89%

use-distributed-optimizer
global-bs 2048 micro-bs 2
elapsed time per iteration (ms): 64638.7 | average overall token/sec : 64888.4 | average token/sec/GPU : 2027.8   GPU显存使用 83.5%

**Comment by li-yi-dong** [comment]
32 卡global-bs 2048 的话就用原来的optimizer 吧

**Comment by silingtong123** [comment]
> 32 卡global-bs 2048 的话就用原来的optimizer 吧

32卡的2048情况下，overlapped-distributed-optimizer就是更差一些吗？还是调大global bs，才能测出效果？如果是的话，大概调多大比较好
