### ISSUE TITLE
pipeline parallel fwd/bwd里面为什么没有调用optimizer.backward_epilogue() 

### ISSUE THREAD

**Issue by jingjie01ai** [alibaba/Megatron-LLaMA#29]
在forward_backward_no_pipelining中实调用了optimizer.**backward_epilogue**() 进行grad的累加拷贝和bucket重置，为什么在forward_backward_pipelining_without_interleaving和forward_backward_pipelining_with_interleaving里面没有调用？

**Comment by li-yi-dong** [comment]
实际是需要的，目前pipeline 还在适配。

**Comment by jingjie01ai** [comment]
> 实际是需要的，目前pipeline 还在适配。

多谢。
今天测试了一下DP2的训练，在timeline中发现reducescatter和backward计算没有并行，可能是什么原因？
<img width="1090" alt="image" src="https://github.com/alibaba/Megatron-LLaMA/assets/143381777/dfee2259-9b0e-4ac2-bee6-8fbcd48efc99">

**Comment by li-yi-dong** [comment]
设置CUDA_DEVICE_MAX_CONNECTIONS=1 会导致无法并行。

**Comment by jingjie01ai** [comment]
> 设置CUDA_DEVICE_MAX_CONNECTIONS=1 会导致无法并行。

那是不是开启overlappedDistOpt的话，就不能使用seq parallel了？
Using sequence parallelism requires setting the environment variable "
                "CUDA_DEVICE_MAX_CONNECTIONS to 1
