### ISSUE TITLE
TypeError: OverlappedDistributedOptimizer.gather_parameters() got an unexpected keyword argument 'skip_if_not_stepped'

### ISSUE THREAD

**Issue by Double-bear** [alibaba/Megatron-LLaMA#40]
请问在训练过程中报了这个错误应该怎么解决？我看overlapped_dist_optimizer里gather_parameters函数并没有要传参数skip_if_not_stepped，请问这个参数可以去除吗？

**Comment by li-yi-dong** [comment]
抱歉，应该在这个commit 中修复了 https://github.com/alibaba/Megatron-LLaMA/commit/25306de84d300b47a3973cd798463ae7d09019bd

**Comment by Double-bear** [comment]
> 抱歉，应该在这个commit 中修复了 [25306de](https://github.com/alibaba/Megatron-LLaMA/commit/25306de84d300b47a3973cd798463ae7d09019bd)

好的，谢谢，还想请问一下我在使用这个megatron训练llama2 70b的模型时发现加载checkpoint时shape不匹配，请问一下现在转换格式的代码是否支持了llama2 70b这样有GQA结构的模型？

**Comment by li-yi-dong** [comment]
目前还不支持GQA

**Comment by Double-bear** [comment]
> 目前还不支持GQA

好的，谢谢
