### ISSUE TITLE
每次GA的backward都需要做通信

### ISSUE THREAD

**Issue by jingjie01ai** [alibaba/Megatron-LLaMA#42]
是否可以最后一个GA(micro batch)，做backward和reduce-scatter并行，前面的GA-microbatch不做通信？现在发现每次GA都通信会导致性能比DistributedOptimizer更差

**Comment by li-yi-dong** [comment]
如果要拆分梯度的话就必须每个micro batch reduce 梯度。可以用省下的显存尝试扩大micro batch，这样并行的空间会更大。

**Comment by jingjie01ai** [comment]
> 如果要拆分梯度的话就必须每个micro batch reduce 梯度。可以用省下的显存尝试扩大micro batch，这样并行的空间会更大。

嗯，理解，如果是bf16相当于增加了2bytes*grad的显存。在某些情况下可能不是瓶颈，大头被分布式DP平均掉了。
主要遇到的问题是，GA较大的时候，可能会增加一些开销导致性能变差：compute/comm不是完美的并行，comm会导致compute稍微增加一些（额外的开销），最后的一个bucket的comm也没有被隐藏。

**Comment by wangjiamang** [comment]
> > 如果要拆分梯度的话就必须每个micro batch reduce 梯度。可以用省下的显存尝试扩大micro batch，这样并行的空间会更大。
> 
> 嗯，理解，如果是bf16相当于增加了2bytes*grad的显存。在某些情况下可能不是瓶颈，大头被分布式DP平均掉了。 主要遇到的问题是，GA较大的时候，可能会增加一些开销导致性能变差：compute/comm不是完美的并行，comm会导致compute稍微增加一些（额外的开销），最后的一个bucket的comm也没有被隐藏。

也可以改成只有最后一次进行overlap，然后按需要配置。

**Comment by jingjie01ai** [comment]
> > > 如果要拆分梯度的话就必须每个micro batch reduce 梯度。可以用省下的显存尝试扩大micro batch，这样并行的空间会更大。
> > 
> > 
> > 嗯，理解，如果是bf16相当于增加了2bytes*grad的显存。在某些情况下可能不是瓶颈，大头被分布式DP平均掉了。 主要遇到的问题是，GA较大的时候，可能会增加一些开销导致性能变差：compute/comm不是完美的并行，comm会导致compute稍微增加一些（额外的开销），最后的一个bucket的comm也没有被隐藏。
> 
> 也可以改成只有最后一次进行overlap，然后按需要配置。

嗯，我先自己改了一下，性能会比distributed optimizer好一点了

**Comment by wangjiamang** [comment]
> > > > 如果要拆分梯度的话就必须每个micro batch reduce 梯度。可以用省下的显存尝试扩大micro batch，这样并行的空间会更大。
> > > 
> > > 
> > > 嗯，理解，如果是bf16相当于增加了2bytes*grad的显存。在某些情况下可能不是瓶颈，大头被分布式DP平均掉了。 主要遇到的问题是，GA较大的时候，可能会增加一些开销导致性能变差：compute/comm不是完美的并行，comm会导致compute稍微增加一些（额外的开销），最后的一个bucket的comm也没有被隐藏。
> > 
> > 
> > 也可以改成只有最后一次进行overlap，然后按需要配置。
> 
> 嗯，我先自己改了一下，性能会比distributed optimizer好一点了

欢迎提pr
