### ISSUE TITLE
是否兼容sequence parallel

### ISSUE THREAD

**Issue by jingjie01ai** [alibaba/Megatron-LLaMA#44]
开启overlappedDistOpt的话，不设置CUDA_DEVICE_MAX_CONNECTIONS，才能并行。
那么是不是不能使用seq parallel了？seq parallel要求这个环境变量为1：
Using sequence parallelism requires setting the environment variable "
"CUDA_DEVICE_MAX_CONNECTIONS to 1

**Comment by mxymxy77** [comment]
我也遇到类似问题了，在这里查了一下，发现https://github.com/alibaba/Megatron-LLaMA/issues/43 我看这个issue和你这个问题是一样的。本质上就是CUDA_DEVICE_MAX_CONNECTIONS不能设置为1导致了很多问题。哪位朋友能帮忙看看吗？

**Comment by wangjiamang** [comment]
可以将CUDA_DEVICE_MAX_CONNECTIONS设置为非1，副产品是计算会变慢，这样在梯度聚合比较少的情况下性能可以提升。
