### ISSUE TITLE
Unable to import Megatron

### ISSUE THREAD

**Issue by Fan-Yunfan** [alibaba/Megatron-LLaMA#51]
在使用权重转换工具的时候，我指定了正确的 Megatron-LLaMA 的位置，但是依旧报下面的错误：
Unable to import Megatron, please specify the path to Megatron using --megatron-path. Exiting.

**Comment by li-yi-dong** [comment]
可以发一下你的脚本吗

**Comment by peixincao** [comment]
老哥问题解决了吗

**Comment by Fan-Yunfan** [comment]
> 可以发一下你的脚本吗

不好意思呀，后面 debug 时候发现原来是路径拼错了

**Comment by Fan-Yunfan** [comment]
> 老哥问题解决了吗

解决啦，是路径问题

**Comment by peixincao** [comment]
> > 老哥问题解决了吗
> 
> 解决啦，是路径问题

可以具体一点吗，我也遇到这个错误了

**Comment by Fan-Yunfan** [comment]
> > > 老哥问题解决了吗
> > 
> > 
> > 解决啦，是路径问题
> 
> 可以具体一点吗，我也遇到这个错误了

就是路径填写错误了，注意看下有没有单词拼写错误或者路径位置不对

**Comment by ZhangEnmao** [comment]
你好，我也遇到了这个问题，我是从 git 上 clone 的 Megatron 项目，执行了python setup.py 脚本，在 /home/Megatron-LM/ 目录下运行权重转化脚本，按理说应该不需要传 --megatron-path 这个参数吧，我也试着正确传入，但是依然报这个错误，如下：
![image](https://github.com/alibaba/Megatron-LLaMA/assets/53638291/69049db1-54f5-4238-b14e-6c03e93951a9)

**Comment by Sun-Xiaohui** [comment]
请问你解决了吗？
